FROM jupyterhub/jupyterhub:$JUPYTERHUB_VERSION

ARG JUPYTERHUB_VERSION

RUN python3 -m pip install --no-cache-dir \dockerspawner==12.* \jupyterhub-nativeauthenticator==1.*

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
